### ISSUE TITLE
Unable to pick up items.

### ISSUE THREAD

**Issue by docHP** [Mordrog/RoR2-ForceItemsEqualShare#1]
You are unable to pick up items when this mod is enabled in the game. You are able to pick up some select items like scrap but any other item dropped by 3d printers or by mobs or by chests are unable to be picked up.

**Comment by Mordrog** [comment]
Yes, yesterday patch seems to have changed something with how items are defined, will have to look at it.

**Comment by Mordrog** [comment]
Should be fixed now
